
--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,sum(purchase_amount) as Revenue
FROM df_customer_behaviour
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,purchase_amount
FROM df_customer_behaviour
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM df_customer_behaviour)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased,ROUND(AVG(review_rating),2) as [Avg Review Rating]
FROM df_customer_behaviour
GROUP BY item_purchased
ORDER BY [Avg Review Rating] DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as [Avg Purchase Amount]
FROM df_customer_behaviour
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,COUNT(customer_id) as total_customers,ROUND(AVG(purchase_amount),2) as [Avg Spend],ROUND(SUM(purchase_amount),2) as [Total Revenue]
FROM df_customer_behaviour
GROUP BY subscription_status
ORDER BY [Total Revenue] DESC

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased, 100*SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END)/COUNT(*) as [Discount Rate]
FROM df_customer_behaviour
GROUP BY item_purchased
ORDER BY [Discount Rate] DESC


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type as (
SELECT customer_id,previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'New'
	 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END AS customer_segment
FROM df_customer_behaviour )

SELECT customer_segment,COUNT(*) AS [No of Customers]
FROM customer_type
GROUP BY customer_segment
ORDER BY [No of Customers] DESC

--Q8. What are the top 3 most purchased products within each category?
WITH item_counts as(
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM df_customer_behaviour
GROUP BY category,item_purchased)

SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3


 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM df_customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group? 
SELECT age_group,SUM(purchase_amount) as total_revenue
FROM df_customer_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC
